### PR TITLE
move starting connection into componentDidMount

### PR DESCRIPTION
**Pull request by Maarten88**
See issue #191

This change moves starting the connection and initializing related subscriptions from the constructor to componentDidMount to accomodate server-side rendering and probably fix issues when re-mounting a component into the dom.

### CODE REVIEW

**Comment by billba** [comment]
Hmmm I think you moved more than is necessary. I think all you need to move is `props.botConnection.start()` - will you try moving just that and see if it solves your problem?

**Comment by Maarten88** [comment]
I think initializing the related subscriptions should move too. They are cleared in componentWillUnmount, so they should be initialized in componentDidMount (says my instinct for symmetry, without having tested the scenario's).

**Comment by billba** [comment]
I'm going to ponder that a bit.

**Comment by Maarten88** [comment]
I've been reading a bit about the React component lifecycle and think my instinct of putting those subscriptions in componentDidMount is correct.

Both componentDidMount and componentWillUnmount do not run when rendering on the server; of course the constructor does run. Leaving those subscriptions in the constructor means they will be created and never get cleared when running on the server. I'm not sure how javascript and node handle this, but I'd expect that to cause a memory leak.

I do think it would be better to start the connection after creating the subscriptions (moving it to the bottom of componentDidMount), but I did not do that in this PR because I did not want to change existing logic or client-side behaviour.

**Comment by billba** [comment]
Great, thanks for researching this.

**Pull request merged**
