### PR TITLE
Send conversation update on connect

### LINKED ISSUE #1606: After connected, Web Chat will synthesize a "conversationUpdate" activity for the user
This is to make up with the platform differences between Direct Line and Emulator.

### PR DESCRIPTION
**Pull request by compulim**
> Fix #1606.

## Background

There are discrepancies between the behavior of Emulator and Direct Line service around `conversationUpdate` event.

The `conversationUpdate` event will tell the bot what members added to this conversation. Currently, we observed there are two activities, one to add bot to the member list, another to add user to the list. In this article, we name them `conversationUpdate([bot])` and `conversationUpdate([user])` respectively.

Emulator will send two `conversationUpdate` event to the bot as soon as possible, one for the bot, another for the user. But Direct Line service will send `conversationUpdate([bot])` to the bot first. Direct Line will send `conversationUpdate([user])` only immediately before the user send their first message.

This PR, will send an empty `conversationUpdate` activity when Web Chat is connected. And it will trigger Direct Line service to send `conversationUpdate([user])`. Thus, on the bot side, the `conversationUpdate([user])` appears to be received as soon as the conversation is started or immediately after `conversationUpdate([bot])`.

## Design considerations

To trigger Direct Line to send `conversationUpdate([user])`, we have two paths:

1. Send `conversationUpdate([])`
2. Send `conversationUpdate([user])`

The first approach is better because it is less likely to affect any existing bots that relies on the `conversationUpdate` activity, because the `membersAdded` property is empty.

But currently, there is a bug in Direct Line service: for all conversations initiated using Direct Line secret (instead of Web Chat secret), Direct Line service will not send `conversationUpdate([user])`, no matter what trigger it.

The second approach, however, will help mimic the missing `conversationUpdate([user])` from the Direct Line platform. However, it may affect existing bots, because if the conversation is instantiated by Web Chat secret (instead of Direct Line secret), the bot will receive two `conversationUpdate([user])` with same user ID. That means, if the bot handled wrongly, it may add two members of same ID to their internal list of members.

We prefer the first approach for a few reasons:

- The problem will be fixed on the service side
- Currently, the `conversationUpdate([user])` is bugged and not available. If the bot developer depends on this activity, they should already have a workaround for this

## Changelog

- `core`: Send `conversationUpdate` activity on connect, by [@compulim](https://github.com/compulim), in PR [#1608](https://github.com/Microsoft/BotFramework-WebChat/pull/1608)

### CODE REVIEW

**Comment by cwhitten** [comment]
The following part of the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Cjsmulti%2Cjswelcomeback) on welcoming users gives me hope that we can mimic a user. By not mimicking the user I'm worried we've missed the mark. 

>Some channels create one conversation update when a user initially connects to that channel, and a separate conversation update only after an initial input message is received from the user. Other channels generate both these activities when the user initially connects to the channel.

Because of this, I hope the bot implementations are anticipating duplicate `conversationUpdate` activities, and we should be OK to move forward with path #2.

**Comment by compulim** [comment]
@cwhitten I have updated the behavior.

This is the dump of activities after:
1. Create a conversation
2. Post an event activity named `webchat/join`

Observed on the bot:

1. `conversationUpdate(bot)`
2. `conversationUpdate(user)` (synthesized)
3. `conversationUpdate(user)` (from Direct Line services)
4. `event(webchat/join)`

```
[start] === conversationUpdate ===
[start] { type: 'conversationUpdate',
[start]   id: 'INpiD7OhpK0',
[start]   timestamp: 2019-01-18T22:31:57.102Z,
[start]   serviceUrl: 'https://directline.botframework.com/',
[start]   channelId: 'webchat',
[start]   from: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   conversation: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   recipient:
[start]    { id: 'webchat-mockbot-dev@M9EstUQ1vCE',
[start]      name: 'webchat-mockbot-dev' },
[start]   membersAdded:
[start]    [ { id: 'webchat-mockbot-dev@M9EstUQ1vCE',
[start]        name: 'webchat-mockbot-dev' } ] }
[start]
[start] === conversationUpdate ===
[start] { type: 'conversationUpdate',
[start]   id: 'AG6NBwUDLKKGBo2gPRJXVs|0000000',
[start]   timestamp: 2019-01-18T22:31:57.443Z,
[start]   serviceUrl: 'https://directline.botframework.com/',
[start]   channelId: 'webchat',
[start]   from: { id: 'r_03c5srv9rb', role: 'user' },
[start]   conversation: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   recipient:
[start]    { id: 'webchat-mockbot-dev@M9EstUQ1vCE',
[start]      name: 'webchat-mockbot-dev' },
[start]   membersAdded: [ { id: 'r_03c5srv9rb' } ],
[start]   locale: 'en-US',
[start]   entities:
[start]    [ { type: 'ClientCapabilities',
[start]        requiresBotState: true,
[start]        supportsListening: true,
[start]        supportsTts: true } ],
[start]   channelData: { clientActivityID: '15478507171020.ysakps1ricp' } }
[start]
[start] === conversationUpdate ===
[start] { type: 'conversationUpdate',
[start]   id: 'KAyEl9OXC8',
[start]   timestamp: 2019-01-18T22:31:57.450Z,
[start]   serviceUrl: 'https://directline.botframework.com/',
[start]   channelId: 'webchat',
[start]   from: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   conversation: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   recipient:
[start]    { id: 'webchat-mockbot-dev@M9EstUQ1vCE',
[start]      name: 'webchat-mockbot-dev' },
[start]   membersAdded: [ { id: 'r_03c5srv9rb' } ] }
[start]
[start] === event ===
[start] { type: 'event',
[start]   id: 'AG6NBwUDLKKGBo2gPRJXVs|0000003',
[start]   timestamp: 2019-01-18T22:31:57.434Z,
[start]   serviceUrl: 'https://directline.botframework.com/',
[start]   channelId: 'webchat',
[start]   from: { id: 'r_03c5srv9rb', role: 'user' },
[start]   conversation: { id: 'AG6NBwUDLKKGBo2gPRJXVs' },
[start]   recipient:
[start]    { id: 'webchat-mockbot-dev@M9EstUQ1vCE',
[start]      name: 'webchat-mockbot-dev' },
[start]   locale: 'en-US',
[start]   channelData: { clientActivityID: '15478507171400.ov7yz6s3xh9' },
[start]   value: { language: 'en-US' },
[start]   name: 'webchat/join' }
[start]
```

**Comment by compulim** [comment]
@cwhitten I have rebased and see if you are okay with the previous comment, about the dump of the activities.

**Comment by cwhitten** [comment]
Let's merge and chat with some internal folks who may appreciate this change and test it out before we include it in a supported release.

**Comment by compulim** [comment]
Need to update MockBot to say a different welcome message.

**Pull request merged**
