### PR TITLE
use IDoCardAction everywhere

### PR DESCRIPTION
**Pull request by danmarshall**
IDoCardAction, YouDoCardAction, WeAllDoCardAction

### CODE REVIEW

**Comment by billba** [comment]
Wait how is this different from #442?

**Comment by danmarshall** [comment]
It's the same, just found more places

**Comment by danmarshall** [comment]
ok, the rabbit hole just went deeper, I added CardActionTypes to the signature. Massive intellisense ensues.

**Comment by billba** [comment]
It's rabbits all the way down.

**Pull request merged**
