### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by corinagum**
doc update

### CODE REVIEW

**Review by stevengum — APPROVED** [review]

**Comment by DDEfromOR** [comment]
I just want to say thank you to @corinagum for the lightening fast turn around on this! Literally less than 10 minutes passed between the customer requesting this update and this PR being opened. ❤️

**Comment by corinagum** [comment]
Ok, 2 tests are failing due to MockBot changes. I'll get those fixed in my AC PR and then re-run CI here for merge.

**Comment by corinagum** [comment]
Passing on azure dev ops, so I am merging this issue

**Pull request merged**
