### PR TITLE
Fixed scroll event trigger problem

### PR DESCRIPTION
**Pull request by vefacaglar**
Fixes #

[#1926](https://github.com/microsoft/BotFramework-WebChat/issues/1926)

## Specific Changes

 

---

-  [ ] Testing Added

### CODE REVIEW

**Comment by corinagum** [comment]
@vefacaglar thanks for the PR. It looks like there may have been a rebase issue that needs to be fixed - your other PR is showing up again in the Files changed section.

I know @compulim is working on this now, so I will defer to him for communication on coordinating the fix.

**Comment by vefacaglar** [comment]
i can’t understand too why these changes showing up again.

thanks for your interest.

**Comment by compulim** [comment]
Thanks for trying to fix the problem.

Although this would fix it, it sounds a bit hacky to fix it by forcing it to scroll to bottom always.

The main problem is when the browser (mainly Chrome variant) resize the element, they send a "scroll" event even the user did not scroll. This is for maintaining the scroll position for better UX in Chrome.

And our scroll to bottom think this scroll event is done by the user. Thus, we stopped being sticky to the bottom because "the user scrolled up, we shouldn't stick to the bottom". But in fact, we should continue to stick to bottom because it is not user's intention to "un-stick".

**Comment by compulim** [comment]
The translation issue is already in. Since this fix is hacky and not fixing the root cause, I am closing this for now. Thanks for the effort.

**Pull request closed without merging**
