### PR TITLE
Update Spanish localization

### PR DESCRIPTION
**Pull request by CKGrafico**
Not sure if you forget, but there is no Spanish translation for xminutes ago.
I copy pasted english version and translated

### CODE REVIEW

**Comment by corinagum** [comment]
Hi @CKGrafico, thanks for the submission! Could you do a few things?
1. Please add the `FAILED_CONNECTION_NOTIFICATION` and `SLOW_CONNECTION_NOTIFICATION` strings on `es-ES.js` 
1. Please add your change to `CHANGELOG.md`
1. Please add your name to the `LOCALIZATION.md`

**Comment by CKGrafico** [comment]
@corinagum done, feel free to give more feedback about  both readmes :)

**Comment by CKGrafico** [comment]
News about this?

**Comment by corinagum** [comment]
@CKGrafico Looks good! Sorry, I was on vacation. :)

**Comment by CKGrafico** [comment]
Thanks for your time @corinagum  :)

**Comment by CKGrafico** [comment]
Updates?

**Comment by corinagum** [comment]
These changes will not be available until the 4.4 release mid-April unless you are using the master bits.

**Pull request merged**
