### PR TITLE
Debump Node.js requirement to 10.14.2

### LINKED ISSUE #3816: botframework-directlinespeech sdk not compatible with spfx 1.11
We have tried out [directline speech sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech) in SharePoint page using Modern script editor webpart. It is working in SharePoint but it will be only specific to that page.

We want to avail bot on each page. For that purpose we are using SPFX Application Customizer Extension. SPFX currently supports only node version 10. 
When we tried out with higher version of botframework-webchat in spfx solution, we found out it have compatibility issues with node version 10. As you can find in screenshot: 
 
image

Botframework-directlinespeech-sdk are not compatible with node version 10, which is only node version supported by SPFX 1.11.
 
image

Can you please provide botframework-directlinespeech-sdk which is compatible with node 10. Or let us know any alternative.

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #3816.

### Fixed

-  Fixes [#3816](https://github.com/microsoft/BotFramework-WebChat/issues/3816). De-bumped Node.js engine requirement for Direct Line Speech SDK to `>= 10.14.2` from `>= 12.0.0`, by [@compulim](https://github.com/compulim) in PR [#3854](https://github.com/microsoft/BotFramework-WebChat/pull/3854)

## Description

De-bump Node.js engine requirement for Direct Line Speech SDK. Based on data from its `package-lock.json`, the minimal version supported is `10.14.2`.

## Specific Changes

- Update `packages/directlinespeech/package.json` to set `engines.node` to `>= 10.14.2`

-  [x] ~I have added tests and executed them locally~
-  [x] I have updated `CHANGELOG.md`
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [x] ~Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] ~Browser and platform compatibilities reviewed
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)
-  [x] ~Documents reviewed (docs, samples, live demo)
-  [x] ~Internationalization reviewed (strings, unit formatting)
-  [x] `package.json` and `package-lock.json` reviewed
-  [x] ~Security reviewed (no data URIs, check for nonce leak)
-  [x] ~Tests reviewed (coverage, legitimacy)

### CODE REVIEW

**Review by corinagum — COMMENTED** [review]
Can you verify our documentation is up to date? I feel like we added recently this info in a doc.

**Comment by compulim** [comment]
> Can you verify our documentation is up to date? I feel like we added recently this info in a doc.

I searched with multiple keywords like `12.0` or `Node.js` but couldn't find it. Can you point it out for me?

**Comment by corinagum** [comment]
Ah okay. Just checked `CONTRIBUTING.md` and it looks like we have `npm` min version but not node. Do you think you could add it?

**Comment by compulim** [comment]
`CONTRIBUTING.md` looks good to me, it said "Node.js of LTS or latest version". That means latest of 10, 12, 14 and 15.

**Review by corinagum — APPROVED** [review]

**Comment by corinagum** [comment]
Pulling this branch and testing locally for sanity check

**Pull request merged**
