### PR TITLE
Fix scroll stickiness issue with Adaptive Card and suggested actions

### LINKED ISSUE #1926: Scroll event is not triggering every time a message is received
here is a video to explain the issue
https://www.loom.com/share/f22dd7020a0a4c5ea53c3a88be87ffee
(pass: webchat)

i'm using master/webchat-es5 (dated 25-Apr-2019) 

Update:
We implemented our own solution as a workaround for this, but it might not be as reliable as a fix in webchat library, pasting the implementation below:

```
var messageListSelector = '#chat-interface ul[role="list"][aria-live="polite"]';
var scrollControl = false;
When action.type === 'DIRECT_LINE/POST_ACTIVITY'
{
scrollControl = true;
}

When action.type === 'DIRECT_LINE/INCOMING_ACTIVITY'
{
if (scrollControl) {
        $(messageListSelector).parent().animate({ scrollTop: $(messageListSelector).height() }, 1000);
    }
    $('#chat-interface input[data-id="webchat-sendbox-input"]').focus();
}
//if user scroll up
$(document).ready(function(){
    $(messageListSelector).bind('mousewheel DOMMouseScroll', function(event){
        event.stopPropagation();
        scrollControl = false;
        var scrollPos = $(messageListSelector).parent().scrollTop();
        var elemHeight = $(messageListSelector).height();
        var srollSkew = elemHeight - scrollPos;
        if (srollSkew > 600 && srollSkew < 636) {
            scrollControl = true;
        }
    });
});
```

### PR DESCRIPTION
**Pull request by compulim**
Fixes #1926.

## Changelog Entry

-  Fix [#1926](https://github.com/microsoft/BotFramework-WebChat/issues/1926). Fixed scroll stickiness issue when submitting an Adaptive Card form with suggested actions opened, by [@compulim](https://github.com/compulim) in PR [#2107](https://github.com/microsoft/BotFramework-WebChat/pull/2107)

## Description

Bringing 2 commits from `react-scroll-to-bottom`:

- Their PR [#24](https://github.com/compulim/react-scroll-to-bottom/pull/24), fixed synthetic `scroll` events crafted by Chrome should not cause stickiness to lose
- Their PR [#22](https://github.com/compulim/react-scroll-to-bottom/pull/22), bumped development dependencies for security vulnerabilities

## Specific Changes

Bumped `react-scroll-to-bottom` to `1.3.2`.

---

-  [x] Tests added

### CODE REVIEW

**Comment by compulim** [comment]
Will add tests.

**Comment by compulim** [comment]
@corinagum I added a new WebDriver condition named `scrollToBottomCompleted`. This can be used to help improve our test reliability.

```js
await driver.wait(scrollToBottomCompleted(), timeouts.scrollToBottom);
```

**Comment by corinagum** [comment]
@tdurnford, do we want to implement the new scrollToBottomCompleted into any of our previous tests?

**Comment by tdurnford** [comment]
Yea we probably want to update this [line](https://github.com/microsoft/BotFramework-WebChat/blob/3b562ff860ce61ded627ceedc6091baef39a3b3c/__tests__/markdown.js#L19) to use the new scrollToBottom timeout instead of making the driver sleep for a second.

**Comment by corinagum** [comment]
@tdurnford  please either file an issue or submit a PR :D

**Pull request merged**
