### PR TITLE
add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by sgellock**
required by all ms oss projects
update to included the latest content

### CODE REVIEW

**Comment by corinagum** [comment]
We already have a code of conduct: https://github.com/microsoft/BotFramework-WebChat/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by compulim** [comment]
We have some broken tests as we recently updated our test bot.

We will babysit this PR and merge this in after we fix the tests.

**Comment by corinagum** [comment]
image
According to the Community Guidelines, the code of conduct should be in `.github`

**Comment by corinagum** [comment]
I updated our code of conduct file based off of guidance from https://docs.opensource.microsoft.com/content/releasing/accepting-contributions.html

**Comment by sgellock** [comment]
Just to be clear, the format I submitted was the exact latest from Microsoft's Open Source Office.  I was deliberate in the exact content in order to be compliant

**Comment by corinagum** [comment]
synced with sgellock to correct PR https://github.com/microsoft/BotFramework-WebChat/pull/3850 to latest verbiage.

**Pull request closed without merging**
