### PR TITLE
Add Chinese translation

### LINKED ISSUE #2620: Update Chinese localization files
There were some updates to localization. Please diff with `en-US.js`.

Please note the change in `uploadFileWithFileSize`, which had a bug

### PR DESCRIPTION
**Pull request by spyip**
Fixes #2620

## Changelog Entry

-  Resolves [#2620](https://github.com/Microsoft/BotFramework-WebChat/issues/2620), update Chinese localization files, by [@spyip](https://github.com/spyip) in PR [#2631](https://github.com/microsoft/BotFramework-WebChat/pull/2631)

## Description

Update Chinese localization files

## Specific Changes

Updated:
- zh-HANT.js
- zh-HANS.js
- zh-YUE.js

---

-  [x] Testing Added

### CODE REVIEW

**Comment by corinagum** [comment]
❤️❤️❤️

**Comment by corinagum** [comment]
@spyip it looks like there are linting errors again, could you take a look? Thanks!

**Comment by compulim** [comment]
Copying the test result here.

```
botframework-webchat-component: /home/vsts/work/1/s/packages/component/src/Localization/zh-HANS.js
botframework-webchat-component:   90:27  error  'uploadFileWithFileSize' is not defined  no-undef
botframework-webchat-component: /home/vsts/work/1/s/packages/component/src/Localization/zh-HANT.js
botframework-webchat-component:   70:29  error  'downloadFileWithFileSize' is not defined  no-undef
botframework-webchat-component:   93:27  error  'uploadFileWithFileSize' is not defined    no-undef
botframework-webchat-component: /home/vsts/work/1/s/packages/component/src/Localization/zh-YUE.js
botframework-webchat-component:   71:29  error  'downloadFileWithFileSize' is not defined  no-undef
botframework-webchat-component:   96:27  error  'uploadFileWithFileSize' is not defined    no-undef
```

**Comment by compulim** [comment]
`timestamp-js-update-timestamp-on-the-fly-3-diff.png`

image

**Pull request merged**
