### PR TITLE
Fix #1835 to verical stacking for SuggestedActions

### LINKED ISSUE #1835: Vertical stacking for SuggestedActions
Is there a way to stack suggested actions be vertically stacked instead of a 'wrap around' carousel? If not, can there be one in the future? :)

### PR DESCRIPTION
**Pull request by spyip**
Fixes #1835 to verical stacking for SuggestedActions

### Added

- Added `suggestedActionLayout` to `defaultStyleOptions`, by [@spyip](https://github.com/spyip), in PR [#2596](https://github.com/microsoft/BotFramework-WebChat/pull/2596)

## Description

Added 'stacked' layout to suggested-actions

## Specific Changes

 

---

-  [x] Testing Added

### CODE REVIEW

**Comment by corinagum** [comment]
@compulim could you review? Thanks :)

**Comment by corinagum** [comment]
@spyip could you look at merge conflicts? Sorry :(

**Comment by corinagum** [comment]
@spyip, one more thing, could you run `npm run eslint` and fix the error? After that we'll FINALLY get this merged in. Thanks for all your help <3

**Comment by anishjaindev** [comment]
Is this change already in production? 
We tried embedding this option, but the suggestedActions still display in carousel.
Use the below cdn link for webchat js.
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>

window.WebChat.renderWebChat({
                    directLine: botConn,
                    styleOptions: {
                        rootHeight: '100%',
                        rootWidth: '100%',
                        hideUploadButton: true,
                        botAvatarImage: '/images/logo.png',
                        botAvatarBackgroundColor: null,
                        suggestedActionBorder: 'solid 2px #D90A07',
                        suggestedActionTextColor: 'blue',
                        suggestedActionHeight: 30,
			suggestedActionLayout: 'stacked',
                        bubbleBackground: '#D90A07',
                        bubbleTextColor: 'white',
                        bubbleFromUserBackground: 'black',
                        bubbleFromUserTextColor: 'white',
                        suggestedActionBorderRadius: 10,
                        bubbleFromUserBorderRadius: 10,
                        bubbleBorderRadius: 10,
                        bubbleMinHeight: 30,
                        sendBoxButtonColor: '#D90A07',
                        transcriptOverlayButtonColor: '#D90A07',
                        sendBoxTextWrap: true,
                        sendBoxHeight: 50,
                        avatarSize: 25,
                        timestampFormat: 'absolute'
                    }
                }, document.getElementById('webchat'));

Could you please suggest why this is not working?

**Comment by compulim** [comment]
@anishjaindev the change is not in production yet. We are planning to ship the next release before mid-December.

If you want to try out the fix with a development build, you can build `webchat.js` by following steps on our [CONTRIBUTING.md](https://github.com/microsoft/BotFramework-WebChat/blob/master/.github/CONTRIBUTING.md). 😉

**Comment by markbosshard** [comment]
can you just provide a screenshot what it will look like? like most people I suppose, we would like to have the buttons only using new lines when there is not enough space on the old line. Will stacked do that behaviour, or will it act differently? See this image for what I would like to have as a behaviour, and in my opinion clearly is the most user-friendly:

image

**Comment by corinagum** [comment]
Please see the test images in the PR. Your example is horizontal with line breaks - the changes that @spyip has incorporated provide a vertical stacking for the suggested actions.

**Comment by markbosshard** [comment]
That sounds very promising to me. Can you tell me, how to do your mentioned "horizontal with linebreaks"? Thanks a lot.

**Comment by anishjaindev** [comment]
Yea, if "horizontal with line breaks" is achievable, could you please suggest what is the hack for that? It does look to be good alternative.

**Comment by corinagum** [comment]
horizontal with line breaks is not currently supported on Web Chat. Since there are already two of you looking for this feature, I recommend filing a feature request on our repo and continuing discussion there. :)

**Comment by anishjaindev** [comment]
I could do small hack for showing suggestion options in "horizontal with line breaks" using the below css workaround. But would like to have some standard approach to achieve the same.

.css-nil > div > * > ul {
	flex-wrap: wrap;
    font-size: small;
}

.css-nil > div > * > ul > li {
	padding: 0px !important;
}

**Pull request merged**
