### PR TITLE
Fix eslint

### PR DESCRIPTION
**Pull request by compulim**
Fixes eslint.

### CODE REVIEW

**Comment by cwhitten** [comment]
the defaultProps are not necessary for these components?

**Comment by compulim** [comment]
Yes, I was thinking the same at the first thought.

But looking closely, we are only passing `children` as prop to the `CarouselActivity`, not the `timestampClassName` because it's from the closure.

Ummm... I think I should refactor `CarouselActivity`/`StackActivity` in their own JS file for performance. My brain was quite working yesterday.

**Comment by corinagum** [comment]
should we close this?

**Comment by compulim** [comment]
No need to close, after twinkling it for a while (made new code, refactor them), I am back to ground zero.

I added a comment because apparently, the code is good. It is not a React functional component, but a middleware function. So no need prop types. 😄

**Pull request merged**
