### PR TITLE
Fix #798 hide upload button

### LINKED ISSUE #798: Remove image upload button in Microsoft BotFramework iFrame
Does the iframe embed has any configuration / support to disable the button ?

botframework

### PR DESCRIPTION
**Pull request by compulim**
New prop `showUploadButton` to hide upload button. It is default to `true`.

### CODE REVIEW

**Comment by deepanigi** [comment]
Where should this property be used in frame or within the node code .

**Comment by ernestoguimaraes** [comment]
Is there anyway to enable upload button using the backhannel feature that, when a specific event was triggered, i show it to the user?

**Comment by compulim** [comment]
@ernestoguimaraes Yes it's possible.

I assume you are embedding Web Chat using React. If you set the `props.showUploadButton` to `false`, the upload button will hide right away. The switch is on-the-fly and does not re-render the control.

So you will listen to backchannel, when you get the signal, you set it in your React code, done. 😃

**Comment by AndrewTilson** [comment]
Is there anyway to disable the upload button when using the webchat iframe?

**Comment by nmssalman** [comment]
still im not clear with that..how can i remove the image upload button from the chat withdow?

**Comment by jvanderbiest** [comment]
> still im not clear with that..how can i remove the image upload button from the chat window?

window.WebChat.renderWebChat({
    ...
    styleOptions: { hideUploadButton: false }
}, document.getElementById('bot'));

**Comment by lumayara** [comment]
> @nmssalman
> 
> > still im not clear with that..how can i remove the image upload button from the chat window?
> 
> ```
> window.WebChat.renderWebChat({
>     ...
>     styleOptions: { hideUploadButton: false }
> }, document.getElementById('bot'));
> ```

This did not work for me :/

**Comment by CharingJC** [comment]
> @ernestoguimaraes Yes it's possible.
> 
> I assume you are embedding Web Chat using React. If you set the `props.showUploadButton` to `false`, the upload button will hide right away. The switch is on-the-fly and does not re-render the control.
> 
> So you will listen to backchannel, when you get the signal, you set it in your React code, done. 😃

@compulim Hello William,

Is there a way to do the configuration for a iframe like the following?
<iframe src='https://webchat.botframework.com/embed/directline-csharp?s=YOUR_SECRET_HERE'  style='min-width: 400px; width: 100%; min-height: 500px;'></iframe>

**Comment by corinagum** [comment]
@CharingJC `iframe` Web Chat does not have a way to modify style options. Only default `iframe` props can be assigned (width, etc).

**Comment by CharingJC** [comment]
Greetings

Thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
