### PR TITLE
Updated comment to include GitHub issue # in postActivity() method of…

### PR DESCRIPTION
**Pull request by stevkan**
## Changelog Entry

Updated comment to include GitHub issue # in `postActivity()` method of `DirectLineSpeech` class, by [@stevkan](https://github.com/stevkan) in PR [#3542](https://github.com/microsoft/BotFramework-WebChat/pull/3542)

## Description

'TODO' comment doesn't include the Github issue #. PR adds the issue # to the comment.

## Specific Changes

Added GitHub issue number to comment on line 74, in DirectLineSpeech.js file.

## Review Checklist

> This section is for contributors to review your work.

-  [ ] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [ ] Browser and platform compatibilities reviewed
-  [ ] CSS styles reviewed (minimal rules, no `z-index`)
-  [ ] Documents reviewed (docs, samples, live demo)
-  [ ] Internationalization reviewed (strings, unit formatting)
-  [ ] `package.json` and `package-lock.json` reviewed
-  [ ] Security reviewed (no data URIs, check for nonce leak)
-  [ ] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

**Comment by corinagum** [comment]
@stevkan sorry for the trouble, could you remove the CHANGELOG entry? We've started trying to not include 'internal' updates that won't affect customers.

**Comment by stevkan** [comment]
@corinagum, are you referring to the CHANGELOG.md entry in the PR description, in the actual PR, or both?

**Comment by tdurnford** [comment]
Just the CHANGELOG.md

**Comment by corinagum** [comment]
ping

**Comment by corinagum** [comment]
Closing due to inactivity

**Pull request closed without merging**
