### PR TITLE
Updated Test Infrastructure

### PR DESCRIPTION
**Pull request by tonyanziano**
## WebChat Test Infrastructure Changes

- Added test harness to the following packages:
  - `packages/bundle`
  - `packages/component`
  - `packages/core`

(Each of these packages now contains a `__tests__` folder that contains any unit tests to be run by Jest.)

- Jest can now be run at the root -- `npm run test` -- which will then run all tests in all packages and generate a code coverage report for WebChat
- Jest can now also be run inside each of the packages independently, however, these will not generate coverage

### CODE REVIEW

**Comment by tonyanziano** [comment]
Would love for some volunteers to perform a clean checkout of this branch and sanity check the tests & coverage. Coverage was looking like about 60% for me locally.

image

**Comment by tonyanziano** [comment]
I was also getting the occasional screenshot mismatch, but it didn't happen often. I believe this was happening on master, but I might be wrong.

**Comment by tonyanziano** [comment]
Rebased and pushed as 1 commit.

**Comment by compulim** [comment]
Tested on my box. It looks really good. Good job!

Notes:
- I tried to add a dummy test under `core` and it merge into code coverage nicely 👍
- Test snapshot fail due to scroll-to-bottom component
   - Unrelated to this PR, we took the screenshot too soon that Chrome did not complete the scroll down, will fix it later

Few things to work on:
- [ ] `component/package-lock.json` weirdly picked up `botframework-webchat@0.0.0-0`
   - I have fixed it, will commit to this PR soon
- [ ] High vulnerability for `jest@<24.1.0` and `lerna@<3.13.1`
   - Will try to bump versions to see
   - Tony said `jest@24` is buggy and not able to work with Babel@7 + TypeScript, will see how to fix it or if it is safe to ignore for now
- [ ] I will slightly clean up `babel-jest-config`, just coding style

**Pull request merged**
