### PR TITLE
Allow implementors to change the WAI-ARIA role of the container (#3658)

### LINKED ISSUE #3658: bug: The WebChat container's role should not always be 'complementary' [screen reader accessibility]
Hi,

 * Relates to :~ #3655.

## Version

* WebChat.js version :~ 4.10.1;
* JS :~ https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js;

## Describe the bug

Sometimes a Chat-bot will be _additional_ content on the Web-page, set apart from the `main` content. However, other times a Chat-bot will be the only or main focus of the Web-page.

In these cases `role=complementary` is not appropriate, and will confuse screen reader users, who may rely on landmark roles for navigation.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

Give implementors / developers the option to modify the container-role via [defaultStyleOptions.js](https://github.com/microsoft/BotFramework-WebChat/blob/v4.11.0/packages/component/src/Styles/defaultStyleOptions.js):

```js
   containerRole: 'complementary', // WAI-ARIA landmark role. Suggestions: 'complementary' or 'region'. Defaults to 'complementary'.
```

The value would be used in :~ https://github.com/microsoft/BotFramework-WebChat/blob/v4.11.0/packages/component/src/BasicWebChat.js#L71;

For example, `role={containerRole}`:

```js
  return (
    <AccessKeySinkSurface ... ... >
      <TypeFocusSinkBox
        className={sinkClassName}
        disabled={disabled}
        ref={transcriptFocusRef}
        role={containerRole}
        sendFocusRef={sendBoxFocusRef}
      >
        // ...
      </TypeFocusSinkBox>
    </AccessKeySinkSurface>
  );
```

Please let me know what you think of this proposal.

Yours,

Nick

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by nfreear**
> Fixes #3658

### Added

-  Resolves [#3658](https://github.com/microsoft/BotFramework-WebChat/issues/3658). Added new `containerRole` to default style options, by [@nfreear](https://github.com/nfreear)

## Description

Added a new attribute `role` to `<ReactWebChat>` and `renderWebChat`, which allows the developer to specify the WAI-ARIA landmark role of the container for the Chat UI. It defaults to `complementary`, which is the currently hardcoded value.

## Specific Changes

1. Modified `<ReactWebChat>` and `<BasicWebChat>` to accept `role` attribute
  - Only [WAI-ARIA landmark roles](https://w3.org/TR/wai-aria/#landmark_roles) are supported
  - Fallback to `complementary` if invalid landmark role is specified

## Tests added

1. Added `accessibility.landmarkRole.valid.html` to make sure role is set correctly
2. Added `accessibility.landmarkRole.invalid.html` to make sure role will fallback to `complementary`

-  [x] I have added tests and executed them locally;
-  [x] I have updated `CHANGELOG.md`;
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [x] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

**Comment by corinagum** [comment]
Hey, thanks for the PR! I've added it to our project kanban even though it's still in draft - this is to keep it on our radar, not to pressure you on time. 🙂

**Comment by nfreear** [comment]
Hi @corinagum,

I see that __BotFramework-WebChat-CI-PR__ has failed above, but when I try to click on [details](https://fuselabs.visualstudio.com/531382a8-71ae-46c8-99eb-9512ccb91a43/_build/results?buildId=202702) I get a `401 Unauthorized` error.

Are you able to screenshot what the failure is please, or give me access or similar?

Note, I'm just waiting for a [response](https://github.com/microsoft/BotFramework-WebChat/issues/3658#issuecomment-760499112) to check my understanding ...;)

Many thanks,

Nick

**Comment by corinagum** [comment]
@nfreear There was one failing test due to timeout as opposed to broken code. I've re-run the pipeline with the expectation that we'll get 100% pass. I'll check on it periodically and rerun if we get more timeouts.

**Comment by nfreear** [comment]
Thanks @corinagum !

**Comment by corinagum** [comment]
@nfreear ping! How's it going? We'd definitely like to get your PR in when you're done with it!

**Comment by compulim** [comment]
I updated the PR as we commented in the original issue.

Instead of using `styleOptions`, we prefer `role` attribute, as commented in [#3658](https://github.com/microsoft/BotFramework-WebChat/issues/3658#issuecomment-769983010).

`useContainerRole` is not needed because:

- Hooks are added only if it benefit developers when they are in composition mode
  - Composition mode = developer bring their own UI, but using Web Chat business logic layer and maybe part of UIs from Web Chat

**Review by corinagum — APPROVED** [review]
LGTM! Thank you @nfreear for the submission :)

**Comment by nfreear** [comment]
Hi @corinagum and @compulim,

Apologies I left this unfinished (caught up in other work I'm afraid :() ... And, thank you for modifying @compulim -- I can see how the modifications make sense!

Best wishes,

Nick

**Comment by corinagum** [comment]
Totally understand about getting caught up! Similarly, we **love** community contributions but it's hard to fit it into our day-to-day schedule, haha. We'd love your participation in other changes if you ever have the time! Thanks again for your help.

**Pull request merged**
