### PR TITLE
Showing successive messages from the same chat-end as a single message

### PR DESCRIPTION
**Pull request by enessoylu**
@billba @compulim @danmarshall  This PR attempts to give a better look for rendered messages. Successive messages from the same chat-end will show up as a single message like popular messaging platforms (Skype, Facebook messenger etc...).

The difference:
diff

Also it has a configurable time window value to show messages separately if their time difference exceeds that value (default 5000 ms):
timeout

### CODE REVIEW

**Comment by cdagli** [comment]
@billba @compulim @danmarshall  Do you think this could be merged, it will be very helpful for some of us.

**Comment by billba** [comment]
@cdagli if you need this right away you can just merge this into your own build

**Comment by corinagum** [comment]
Hi there! Grouping timestamps has been implemented into v3 and v4. I'm so sorry we didn't give feedback on this PR until now.

**Comment by Naveenbc** [comment]
How do I get this feature in JS version?

**Comment by enessoylu** [comment]
@Naveenbc this is not merged. You can pull my branch and after that build and use the botchat.css and botchat.js

**Comment by corinagum** [comment]
@Naveenbc timestamps are also available in Web Chat v4. Please feel free to look at our sample: [07.a.customization-timestamp-grouping](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/07.a.customization-timestamp-grouping)

**Comment by Naveenbc** [comment]
Thank You So much @corinagum You saved my day. Thanks @enessoylu for replying.

**Pull request closed without merging**
