### PR TITLE
Move @types to devDependencies

### PR DESCRIPTION
**Pull request by LarsLiden**
Prevents compile error when using different version of react

### CODE REVIEW

**Comment by LarsLiden** [comment]
@eanders-MS - look reasonable?

**Comment by eanders-MS** [comment]
Change looks fine, but please preserve alphabetical order.

**Comment by eanders-MS** [comment]
@danmarshall does this look ok to you?

**Comment by danmarshall** [comment]
I am going to guess not. Here's what you should do to verify:
1. Get a clean clone of this.
2. Try to build.

I surmise that you wouldnt be able to build, because the TS compiler won't know what React is. So then, the dev is forced into installing React on their own.

**Comment by danmarshall** [comment]
Actually, I correct myself: 
Create another project that uses Web Chat as a dependency. This new project would not build.

**Comment by danmarshall** [comment]
See #598 and #705 which is a dupe of this PR

**Comment by danmarshall** [comment]
I do believe React should be a Peer Dependency. There will probably be some tweaking to the build steps if we decide to do that.

**Comment by compulim** [comment]
`peerDependencies` is the only way to do that. NPM will warn if the user did not select a version of React while they do `npm install`.

For your "create another project that uses Web Chat...", I will check it out but it should be fine. Because as we `npm install botframework-webchat` in, we are bringing the pre-built version.

**Comment by corinagum** [comment]
Sorry that we never got this PR in. But in good news, this is resolved in v4! :)

**Pull request closed without merging**
