### PR TITLE
RTL support && Hebrew language - Part 2

### LINKED ISSUE #1976: [IC3] Request: RTL support and localization for Hebrew, Urdu, and Arabic (+ info on localization contributions)
> VSTS #1663019

[edited by @corinagum)

Feature request: RTL support for languages like Hebrew, Urdu, and Arabic, as well as localization support for Hindi and the previously listed languages.
----

[Question]
is it possible speech to text of google is implement in bot frame work V4 like hindi and urdu and arabic?

### PR DESCRIPTION
**Pull request by geea-develop**
Fix #1976

### CODE REVIEW

**Comment by corinagum** [comment]
@geea-develop sorry again for the delay on this PR! I just wanted to let you know that our team is still aware of your PR and how important it will be to verify RTL support. We've decided to keep this on the burner for now and hopefully we can give it the time it deserves soon. :) Thanks again for the submission.

**Comment by armendu** [comment]
Hi, I wanted to know the status of this Pull request? Me and my team working with BotFramework-WebChat would really benefit from it. Thank you for your hard work!

**Comment by cwhitten** [comment]
@armendu we'll be looking to prioritize and wrap up this effort in one of our upcoming releases.

**Comment by corinagum** [comment]
This PR is stale, so I am closing this issue. We will implement this in the future **with original credit**, and tracking can be found at #1976

**Pull request closed without merging**
