### PR TITLE
Remove download links from user-uploaded attachments without thumbnails

### LINKED ISSUE #2248: Remove download link from user uploaded attachments
Attachments sent from the user would not have any working links to download the content again.

Also note MP3 files may get rendered as `<audio>`.

### PR DESCRIPTION
**Pull request by compulim**
Fixes #2248.

### Fixed

-  Fix [#2248](https://github.com/microsoft/BotFramework-WebChat/issues/2248). Remove download links from user-uploaded attachment without thumbnails, by [@compulim](https://github.com/compulim) in PR [#2262](https://github.com/microsoft/BotFramework-WebChat/pull/2262)

## Description

We disabled links to user-uploaded attachment on our servers. This PR disable the links on the client if the attachment does not have a thumbnail. The thumbnail work is in PR #2206.

It would looks like this:

image

## Specific Changes

- Add new `UploadAttachment` renderer, which is very similar to `DownloadAttachment` but without links
- Insert `UploadAttachment` in the attachment middleware, will use the renderer if the attachment is from user and does not have a thumbnail

---

-  [ ] Testing Added

### CODE REVIEW

**Comment by corinagum** [comment]
We probably need tests. Should all current tests be passing right now?

**Comment by compulim** [comment]
Should wait until #2206 is merged.

**Comment by narik1989** [comment]
Hi,

What is the solution for this to work? i am using the latest webchat.js in my web chat and still i see the download icon for the uploaded documents. Can anyone provide me some help here. 

enableUploadThumbnail is set to false. Do i have to add anything else to style options or am i missing something here?

**Comment by corinagum** [comment]
If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Pull request merged**
