### PR TITLE
Bump botframework-directlinejs in all packages/samples

### PR DESCRIPTION
**Pull request by cwhitten**

### CODE REVIEW

**Comment by compulim** [comment]
Looks like this is missing `package-lock.json`, causing errors in `npm ci` in Travis CI.

If you have `package-lock.json`, please submit along. Otherwise, please do not modify `package.json` manually, always use either `lerna add` or `npm install` for dependency management. And also make sure `npm` is of latest version so it emit latest format of `package-lock.json`.

**Comment by cwhitten** [comment]
Ah, yeah this isn't ready. The lockfile generation on Mac looks to be doing something different than lockfile generation on Windows and I was inspecting the diff a bit before pushing them up.

**Comment by compulim** [comment]
Yea, it upset a lot of people when the fix is not in 6.4.1, including me.

As long as we are adding more `optional` than removing them, I am fine with it. And AFAIK, `npm ci` is fine with the missing `optional` too.

**Comment by cwhitten** [comment]
closing in lieu of https://github.com/Microsoft/BotFramework-WebChat/pull/1544

**Pull request closed without merging**
