### PR TITLE
Server side localized French example in a popup

### PR DESCRIPTION
**Pull request by salesucation**
The bot framework is amazing! I needed French in Canada and thought that it would be better to do the translation on the server side. I had to do a little change to the last change to History.tsx so that I could have a popup.

### CODE REVIEW

**Comment by billba** [comment]
Thanks for the submission.

There is a lot going on in this pull request, and I can't take it as-is. Let me explain why:
1. There are multiple features. e.g. popup sample and moving strings into props. The best PRs are focused on solving one problem at a time.
2. Typically, changes/additions to behavior of any open-source repo should first be proposed as issues, discussed, and approved by the project leads before a PR is submitted.
3. This PR contains changes that just consist of altering the coding style of unrelated code, e.g. removing the visual padding from object declaration. You don't have to agree with a project's coding style, but consistency within the project is the most important thing. Also, style changes mixed with feature work make it hard to understand which changes are relevant.
4. You mention "French" in the title but there is nothing specific to French in the PR.
5. Your sample code uses a set of new dependencies which makes it hard to understand if it is demonstrating a general-purpose capability (putting WebChat in a modal dialog) or just solving a specific problem (using WebChat with the specific library you used)

I'm closing this PR as I can't merge it for the reasons described above. If you'd like to pursue getting your changes into this project, the next step would be to open separate issues for each of the problems you faced so that we can understand them better and discuss the best solution. Each problem should be described in a general-purpose way so that we understand how it might affect other customers of the library.

All that said, I have some specific questions about your ideas. I'd love to see you open issues to discuss these:
1. Why does it make sense to pass localized strings in via props instead of hard-coding them into the client as we have done? Do you expect any of these strings to change from instance to instance?
2. Can you explain why your changes were necessary to put WebChat, generically, in a modal dialog?

Finally, I would very much welcome a PR adding French translations to Strings.ts.

**Comment by salesucation** [comment]
Thanks for looking at this. I am answering your questions, and then I will move on.

1) It makes sense for me to have the strings in the props, because I am translating from a much larger set of languages on the fly on the server. My Bot translates from the language spoken by the customer service rep to the language spoken by the customer on the fly so it is important that the webchat supports all of the languages that my bot supports on the other channels.

2) I had to make the change to History.tsx because of the last commit by Bill Barnes (73ee08ae2c8a59059cd17d20adc79ded1d56217d). That commit depends on `const maxContentWidth = (this.carouselActivity.messageDiv.offsetParent as HTMLElement).offsetWidth - paddedWidth;`. I don't have an offsetParent as I haven't rendered yet with the popup.

thanks again

Rich

**Comment by salesucation** [comment]
Sorry about the formatting change in History.tsx. I let visual studio code do that by accident. The only relevant changes to History.tsx are:

```
     componentDidUpdate() {
 -        if (this.props.format.carouselMargin == undefined) {
 -            // After our initial render we need to measure the carousel width
 -
 -            // Measure the message padding by subtracting the known large width
 -            const paddedWidth = measurePaddedWidth(this.carouselActivity.messageDiv) - this.largeWidth;
 -
 -            // Subtract the padding from the offsetParent's width to get the width of the content
 -            const maxContentWidth = (this.carouselActivity.messageDiv.offsetParent as HTMLElement).offsetWidth - paddedWidth;
 -            
 -            // Subtract the content width from the chat width to get the margin.
 -            // Next time we need to get the content width (on a resize) we can use this margin to get the maximum content width
 -            const carouselMargin = this.props.format.chatWidth - maxContentWidth;
 -            
 -            konsole.log('history measureMessage ' + carouselMargin);
 -
 -            // Finally, save it away in the Store, which will force another re-render
 -            this.props.dispatch<FormatAction>({ 
 -                type: 'Set_Measurements',
 -                carouselMargin
 -            });
 -
 -            this.carouselActivity = null; // After the re-render this activity doesn't exist
 -        }
 +        if (this.carouselActivity != null) {
 +            if (this.carouselActivity.messageDiv.offsetParent != null &&
 +                this.props.format.carouselMargin == undefined) {
 +                // After our initial render we need to measure the carousel width
 +
 +                // Measure the message padding by subtracting the known large width
 +                const paddedWidth = measurePaddedWidth(this.carouselActivity.messageDiv) - this.largeWidth;
 +
 +                // Subtract the padding from the offsetParent's width to get the width of the content
 +                const maxContentWidth = (this.carouselActivity.messageDiv.offsetParent as HTMLElement).offsetWidth - paddedWidth;
 +
 +                // Subtract the content width from the chat width to get the margin.
 +                // Next time we need to get the content width (on a resize) we can use this margin to get the maximum content width
 +                const carouselMargin = this.props.format.chatWidth - maxContentWidth;
  
 +                konsole.log('history measureMessage ' + carouselMargin);
 +
 +                // Finally, save it away in the Store, which will force another re-render
 +                this.props.dispatch<FormatAction>({
 +                    type: 'Set_Measurements',
 +                    carouselMargin
 +                });
 +
 +                this.carouselActivity = null; // After the re-render this activity doesn't exist
 +            }
 +            else{
 +                const carouselMargin = 0;
 +                this.props.dispatch<FormatAction>({
 +                    type: 'Set_Measurements',
 +                    carouselMargin
 +                });
 +                
 +            }
 +
 +        }
```

As I said. Very sorry about the other and my sloppiness.

**Comment by billba** [comment]
> it is important that the webchat supports all of the languages that my bot supports on the other channels

I much prefer to update WebChat to support all these languages in its UX natively.

>  I don't have an offsetParent as I haven't rendered yet with the popup.

This is interesting. Please raise it as a separate issue. If this breaks your case it probably breaks server-side rendering as well.

**Pull request closed without merging**
