### PR TITLE
Solving Issue 1904

### LINKED ISSUE #1904: Add Bot/User Avatar Initials Text and Background Color to defaultStyleOptions
I want to customize the background and text color of Bot/User Avatar Initials based on the overall color scheme of the webchat ui. 
I only see customizing the css as a solution but getting it from defaultStyleOptions would be way to benefit everyone.

### PR DESCRIPTION
**Pull request by reyesrico**
Fixes #1904 

## Changelog Entry

 Adding new styleOptions for user and bot avatars.

## Description

Adding new styleOptions for user and bot avatars:
botAvatarBackgroundColor, botAvatarBorderRadius, botAvatarFont, botAvatarFontSize, botAvatarTextColor, userAvatarBackgroundColor, userAvatarBorderRadius, userAvatarFont, userAvatarFontSize, userAvatarTextColor.

## Specific Changes

Updated Avatar (Activity and StyleSet components) and defaultStyleOptions files to receive new styleOptions params. Also it was updated index.html  from samples/04.a 
---

-  [ ] Testing Added
   Updated index.html from samples/04.a

### CODE REVIEW

**Comment by tdurnford** [comment]
Thank you for your contribution! The Web Chat Team really appreciates your willingness to help; however, I think this issue was already fixed in https://github.com/microsoft/BotFramework-WebChat/pull/2384.

**Comment by corinagum** [comment]
Carlos! Why is this PR 100+ files?? xD

**Comment by corinagum** [comment]
@reyesrico 
Carlitos, I'm going to close this PR, since we already have the code implemented. There are 1 or 2 pieces missing though, so let's resume conversation on #1904.

**Comment by corinagum** [comment]
See #2447

**Pull request closed without merging**
