### PR TITLE
[Wait for 4.6] Move to Redux hooks

### LINKED ISSUE #2345: Convert BasicWebChat to React Hooks
## Feature Request
Related to: https://github.com/microsoft/BotFramework-WebChat/pull/2322

`BasicWebChat` component has not yet been converted to Hooks. This issue is for tracking that work. :)

### PR DESCRIPTION
**Pull request by compulim**
Fixes #2345.

## Changelog Entry

(TBD)

## Description

`react-redux@7.1.1` finally support [partitioned Redux hooks in their #1309](https://github.com/reduxjs/react-redux/pull/1309)! 🎉 It was just released the day before yesterday!

Thanks for @corinagum on the *BIG* push of moving from class components to functional components. So we can make this push today. 💪🏻

We are also moving away from HOC and use hooks intensively. This will reduce code complexity and highly improve readability.

Now it is super easy to build a new UI component without too much reading into Web Chat code, thanks to the React hooks pattern.

For example, if you want to build a button that would open microphone.

```js
import { useStartDictate } from 'botframework-webchat-component';

const StartRecordingButton = () => {
  const startDictate = useStartDictate();

  return <button onClick={startDictate}>Turn on microphone</button;
}
```

And put this `<StartRecordingButton>` inside any part of Web Chat, it will automatically wired up.

Also, the `propTypes` on the component is very clean now. No more unnecessary-but-required-by-ESLint props from the context or store.

## Specific Changes

- Added hook for every functionality
   - Every `use*` hook is small and we are able to shuffle the physical location of the actual function if we want to, without breaking the user
      - We currently have things not located accurately, they are in React context and Redux store. Some appears on both of them (e.g. language).
   - Redux hooks requires us to make smaller hook and composite them into a bigger one
- Update all components that use `connectToWebChat()` into `useSelector(WebChatReduxContext)` and `useContext(WebChatContext)`
- Add deprecation notes to all `connect*` HOC functions

---

-  [x] Revisit every component and hook to make sure the exposed surface as lean-and-mean as possible
-  [x] Update samples (at least one of them) to show off the ability to use hooks
   - [x] `samples/09.customization-reaction-buttons`
   - [x] `samples/10.b.customization-password-input`
   - [x] `samples/13.customization-speech-ui`
   - [x] `samples/21.customization-plain-ui`
-  [x] Document some fundamental differences between `connect*` and `use*`
   -  For `useComponent` (e.g. `useMicrophoneButton`), we no longer expose `language`
-  [x] Consider a dedicated namespace inside our package for the hooks
   -  For example, `import { useActivities } from 'botframework-webchat-component/lib/hooks`, and not exposing it at the root level
-  [x] Test under IE11
-  [x] ~(Optional) Might be a good idea to understand more about the performance gain~
-  [x] ~(Optional) Experiment on how to add a new UI component to Web Chat in the new world~
   - Sample `10.b.customization-password-input` and `21.customization-plain-ui` are two great ways to explore the world of hooks
-  [x] Testing Added

### CODE REVIEW

**Comment by corinagum** [comment]
ping!

**Comment by compulim** [comment]
We need more samples. `21.customization-plain-ui` is a great way to show off the simplicity of React Hooks!

**Comment by compulim** [comment]
Spent a lot of time revisiting every single hook. There were stupidity but all are fixed now.

Should write down my rationale and thoughts on what to hook and how, in `HOOKS.md`.

**Comment by compulim** [comment]
Couldn't believe I refactored 150 files in a single commit and I only have 2 build-time errors. No runtime errors. 💪🏻

**Comment by compulim** [comment]
Finally, a well-defined (and hopefully well-thought) Web Chat API. 💪🏻

For starter, please read `HOOKS.md` first. All hooks defined are in some ways used by Web Chat UI. 1P = 3P.

**Pull request closed without merging**
