### PR TITLE
Adding sample for hosting WebChat in an Angular application

### LINKED ISSUE #1423: Sample: Host Web Chat with Angular5
@omarsourour, let's coordinate to make sure we are on the same page for how to implement this sample.

### PR DESCRIPTION
**Pull request by omarsourour**
Fixes #1423

### CODE REVIEW

**Comment by corinagum** [comment]
Looks good to me! Can you add an entry to `CHANGELOG.md`? Thanks for all the help.

**Comment by omarsourour** [comment]
@corinagum Done, added entry in ChangeLog. Please give it a look :)

**Comment by corinagum** [comment]
Oops! Sorry Omar, a couple more things
- could you update the samples list on the root README.md
- update samples/README.md with same change

Otherwise, looks good and I will merge after your final commit. Sorry about that!

**Comment by omarsourour** [comment]
@corinagum Done :) .. Please take a look

Also, may I ask/suggest why not have the root README.md link to the samples/README.md? :)

**Comment by corinagum** [comment]
@omarsourour oh is there a way to automatically update one and it will update the other? If so please let me know how!

Thank you!

**Pull request merged**
