### PR TITLE
Update md files

### PR DESCRIPTION
**Pull request by corinagum**
Fixes N/A

## Changelog Entry

 
N/A
## Description

- Change language of `Add` section of CHANGELOG.md
- lint md files

## Specific Changes

 

---

-  [ ] Testing Added

### CODE REVIEW

**Comment by tdurnford** [comment]
Do we want to use 'resolve #xxx', 'resolves #xxx', or 'resolved #xxx'?

**Comment by corinagum** [comment]
@tdurnford I intentionally chose 'resolve' since it matches with 'fix', what do you think?

**Comment by tdurnford** [comment]
@corinagum I like resolves.

**Comment by corinagum** [comment]
@tdurnford okay so that would mean I'm fixing all the 'fix's to 'fixes', sound g?

**Comment by tdurnford** [comment]
@corinagum I think it should be 'fixes' anyway.

**Pull request merged**
